variables:
  SECURE_FILES_DOWNLOAD_PATH: "./android/app/"

.android-build:
  tags:
    - docker
  before_script:
    # Gitlab secret files loader
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - printenv
    - "cp $ENV ./env.js"
    - "cp ./Fastfile fastlane/Fastfile"
    - yarn install --frozen-lockfile --cache-folder .yarn
    - export VERSION_NAME=$(npm pkg get version | tr -d \")
    - export VERSION_CODE=$CI_PIPELINE_IID
    - echo $VERSION_NAME
    - echo $VERSION_CODE

android-publish-firebase:
  extends: .android-build
  stage: android
  image: niklucky/gitlab-fastlane-android-android:latest
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
  environment: develop
  rules:
    - if: ($CI_COMMIT_TAG =~ /^android-dev-\d+.\d+.\d+-?.*$/)
      when: always
    - when: never
  script:
    - "fastlane android publish_firebase_app"
    - "fastlane android check_firebase"
  artifacts:
    paths:
      - android/app/build/outputs/bundle/releaseStaging/app-releaseStaging.aab

android-publish-playstore:
  extends: .android-build
  stage: android
  image: niklucky/gitlab-fastlane-android-android-android:latest
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
  environment: main
  rules:
    - if: ($CI_COMMIT_TAG =~ /^android-release-\d+.\d+.\d+-?.*$/)
      when: always
    - when: never
  script:
    - "fastlane android internal"
  artifacts:
    paths:
      - android/app/build/outputs/bundle/release/app-release.aab

android-promote-beta:
  stage: promote
  tags:
    - docker
  image: niklucky/gitlab-fastlane-android-android:latest
  environment: main
  rules:
    - if: ($CI_COMMIT_TAG =~ /^android-release-\d+.\d+.\d+-?.*$/)
      when: manual
    - when: never
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - "fastlane android promote_beta"

android-promote-production:
  stage: promote
  tags:
    - docker
  image: niklucky/gitlab-fastlane-android:latest
  environment: main
  rules:
    - if: ($CI_COMMIT_TAG =~ /^android-release-\d+.\d+.\d+-?.*$/)
      when: manual
    - when: never
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - "fastlane android promote_production"
