.code-push:
  tags:
    - docker
  stage: code-push
  environment: $CI_COMMIT_BRANCH
  rules:
    - if: ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main")
  image: niklucky/gitlab-appcenter:latest
  before_script:
    - "cp $ENV ./env.js"
    - yarn install --frozen-lockfile
    - appcenter login --token $APPCENTER_ACCESS_TOKEN_FULL
  after_script:
    - appcenter logout

code-push-ios:
  extends: .code-push
  script:
    - "yarn ci:codepush:ios:${CI_COMMIT_BRANCH}"
    - "yarn codepush:ios:version"
    - "notify_telegram_codepush.js ios"
    - "notify_telegram_codepush.js ios chat_id=${TELEGRAM_CHAT_ID_ADDITIONAL}"

code-push-android:
  extends: .code-push
  script:
    - "yarn ci:codepush:android:${CI_COMMIT_BRANCH}"
    - "yarn codepush:android:version"
    - "notify_telegram_codepush.js android"
    - "notify_telegram_codepush.js android chat_id=${TELEGRAM_CHAT_ID_ADDITIONAL}"
