.code-push:
  tags:
    - docker
  stage: code-push
  environment: $CI_COMMIT_BRANCH
  rules:
    - if: ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main")
  image: niklucky/gitlab-codepush:latest
  before_script:
    - "cp $ENV ./env.js"
    - yarn install --frozen-lockfile
    - export VERSION_NAME=$(npm pkg get version | head -1 | tr -d \")
    - export VERSION_CODE=$CI_PIPELINE_IID
    - echo $VERSION_NAME
    - echo $VERSION_CODE
    - code-push-standalone login --accessKey $CODEPUSH_ACCESS_KEY $CODEPUSH_SERVER_URL
  script:
    - "yarn ci:codepush:${PLATFORM}:${CI_ENVIRONMENT_NAME} -t $VERSION_NAME"
    - "code-push-standalone deployment list --app $APPCENTER_APP --disable-telemetry --output json >> ${PLATFORM}_version.json"

    - "notify_telegram_codepush.js ${PLATFORM}"
    - "notify_telegram_codepush.js ${PLATFORM} chat_id=${TELEGRAM_CHAT_ID_ADDITIONAL}"
  after_script:
    - code-push-standalone logout

.code-push-ios:
  extends: .code-push
  variables:
    PLATFORM: ios
    APPCENTER_APP: $APPCENTER_IOS_APP

.code-push-android:
  extends: .code-push
  variables:
    PLATFORM: android
    APPCENTER_APP: $APPCENTER_ANDROID_APP
